name: Build prometheus

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-prometheus:
    runs-on: self-hosted
    steps:
      - uses: TooMuch4U/actions-clean@v2.1
      - uses: actions/checkout@v3

      - run: |
          docker build -f ./prometheus/Dockerfile \
          -t ${{ secrets.DOCKER_REGISTRY }}/twir/prometheus:latest \
          --cache-from type=gha,scope=twir-prometheus \
          --cache-to type=gha,mode=max,scope=twir-prometheus ./prometheus

          docker push ${{ secrets.DOCKER_REGISTRY }}/twir/prometheus:latest
